spring:
  data:
    couchbase:
      connection-string: localhost
      user-name: admin
      password: password
      bucket-name: orders
  kafka:
    bootstrap-servers: localhost:9092
server:
  port: 8082
